GET http://localhost:8084/api/exercises
Authorization: Basic 1

###
GET http://localhost:8084/api/exercises/1
Authorization: Basic 1

###
POST http://localhost:8084/api/exercises
Content-Type: application/json
Authorization: Basic 1

{
  "userId": 1,
  "activityId": 1,
  "startTime": "2024-01-01T00:00:00Z",
  "duration": 3600
}

###
DELETE http://localhost:8084/api/exercises/5
Authorization: Basic 1
