server:
  port: 8084
spring:
  datasource:
    url: jdbc:h2:mem:fitdb
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
  h2:
    console.enabled: true

tracker.system-user-id: 0
