server:
  port: 8083
spring:
  datasource:
    url: jdbc:h2:mem:hello-db
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

hello.message: Hello from application.yaml

